name: React on README.md Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  react-on-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all README markdown files
        id: changed-readme-markdown-files
        uses: chemodun/changed-files@0.1.0
        with:
          # Avoid using single or double quotes for multiline patterns
          files: src\/.*\/README\.md

      - name: Install python3
        if: steps.changed-readme-markdown-files.outputs.any_changed == 'true'
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Clone markdown-to-bbcode repository
        if: steps.changed-readme-markdown-files.outputs.any_changed == 'true'
        run: |
          git clone https://github.com/chemodun/markdown-to-bbcode-simple.git

      - name: Process README.md changes
        if: steps.changed-readme-markdown-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-readme-markdown-files.outputs.all_changed_files }}
          DELETED_FILES: ${{ steps.changed-readme-markdown-files.outputs.deleted_files }}
        run: |
          git config user.name "Chem O'Dun"
          git config user.email "chemodun@gmail.com"
          for readme in ${CHANGED_FILES}; do
            output_file="${readme%.md}.html"
            echo "Converting $readme to $output_file"
            docker run --rm -v $(pwd):/workspace pandoc/core:3.5 --from=markdown --to=html --standalone=true --output="/workspace/$output_file" "/workspace/$readme"
            if [[ $? -ne 0 ]]; then
              echo "Error converting $readme to $output_file" >&2
            else
              echo "Converted $readme to $output_file"
              git add "$output_file"
              if [[ $? -ne 0 ]]; then
                echo "Error adding $output_file to git" >&2
              else
                echo "Added $output_file to git"
              fi
            fi
            relative_path=$(dirname $readme)
            for conversion_type in egosoft nexus steam; do
              echo "Converting $readme to $conversion_type"
              python3 markdown-to-bbcode-simple/markdown_to_bbcode.py -t $conversion_type -o "docs" "$readme" --skip-toc
              if [[ $? -ne 0 ]]; then
                echo "Error converting $readme to $conversion_type" >&2
              else
                echo "Converted $readme to $conversion_type"
                git add "$relative_path/docs/README.$conversion_type"
                if [[ $? -ne 0 ]]; then
                  echo "Error adding $relative_path/docs/README.$conversion_type to git" >&2
                else
                  echo "Added $relative_path/docs/README.$conversion_type to git"
                fi
              fi
            done
          done
          for readme in ${DELETED_FILES}; do
            file_name=$(basename $readme)
            relative_path=$(dirname $readme)
            if [[ file_name == "README.md" ]]; then
              for conversion_type in egosoft nexus steam; do
                file_to_delete="${relative_path}/docs/README.$conversion_type"
                if [[ -f "$file_to_delete" ]]; then
                  echo "Deleting $file_to_delete"
                  git rm "$file_to_delete"
                  if [[ $? -ne 0 ]]; then
                    echo "Error deleting $file_to_delete" >&2
                  else
                    echo "Deleted $file_to_delete"
                  fi
                fi
              done
              if [[ -f "$relative_path/docs/README.html" ]]; then
                echo "Deleting $relative_path/docs/README.html"
                git rm "$relative_path/docs/README.html"
                if [[ $? -ne 0 ]]; then
                  echo "Error deleting $relative_path/docs/README.html" >&2
                else
                  echo "Deleted $relative_path/docs/README.html"
                fi
              fi
            fi
          done
          rm -rf markdown-to-bbcode-simple

      - name: Commit and push changes
        if: steps.changed-readme-markdown-files.outputs.any_changed == 'true'
        run: |
          if [[ -n $(git status -uno --porcelain) ]]; then
            git commit -m "docs(README): Update README's files"
            git push
            if [[ $? -ne 0 ]]; then
              echo "Error pushing changes" >&2
            else
              echo "Changes pushed successfully"
            fi
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}